### DISCUSSION TITLE
is it possible to make a httppost every x minutes to a custom adress?

### DISCUSSION THREAD

**Discussion by cubensos** [ajfriesen/ESPHome-AirGradient#19] [Q&A] [answered]
i would like to store the data on a remote server. is that possible?

**Comment by ajfriesen** [comment]
It's a esp8266 so you can program your own firmware to do what you desire.

You can use Prometheus to scrape the values from the esp with esphome:

https://esphome.io/components/prometheus.html

I am not sure if you can push any data since this would require some sort of client.
Not sure though.

Depends on what you mean with "to a remote server".

There is also the [http request ](https://esphome.io/components/http_request.html).
With this you should be able to send data somewhere.

**Reply by Michael-Frank** [reply, marked as answer]
@cubensos 
@ajfriesen  outline a method for a "pull-based" flow.

Here is one for a "pushed-based" flow. Use whatevers suites your needs or what is supported by your remote server.

To Periodically send a Post request, use "interval" with a `http_request.post` configuration block
See: https://esphome.io/components/http_request.html#post-body-in-json-format-syntax-2

Outline:
````yaml
interval:   
   # Send data to your custom API server 
   - interval: 5min 
     then: 
       - http_request.post: 
           url: !lambda | 
             return "http://<your-custom-url>:<yourPort>/<yourEndpoint>"; 
           headers: 
             Content-Type: application/json 
           # Note: can't use the built-in json encoder here because it does not support nested objects. 
           body: !lambda | 
             String jsonString; 
             StaticJsonDocument<1024> doc; 
             // ... create your json document strucutre here
             // ...

             // Serialize the JSON document into the string 
             serializeJson(doc, jsonString); 
             // Convert String to std::string 
             std::string stdJsonString(jsonString.c_str()); 
             return stdJsonString; 
```

Full blown example as in this PR  https://github.com/ajfriesen/ESPHome-AirGradient/pull/17 :
https://github.com/ajfriesen/ESPHome-AirGradient/blob/632c81b2c83bec27ae6bb63a5fe5537389d807ca/air-gradient-open-air.yaml#L382-L445
