### DISCUSSION TITLE
platform: sgp4x

### DISCUSSION THREAD

**Discussion by TurboTronix** [ajfriesen/ESPHome-AirGradient#20] [General]
I added the following code to your air-gradient-pro-diy.yaml but I keep getting the following error in the log:
```
[20:13:54][W][component:204]: Component sgp4x.sensor took a long time for an operation (0.06 s).
[20:13:54][W][component:205]: Components should block for at most 20-30ms.
```

Code that was added:
```
- platform: sgp4x
    voc:
      id: VOC
      name: "VOC Index"
    nox:
      id: NOx
      name: "NOx Index"
    compensation:
      humidity_source: humidity
      temperature_source: temp
```

Board used:
https://www.aliexpress.com/item/1005005631456633.html?spm=a2g0o.order_list.order_list_main.47.796b18022gHmV0
*I removed the resistors on my SHT board as follows to make it work: https://www.airgradient.com/images/diy/pull-up.jpg

Using PCB V4.2
