### DISCUSSION TITLE
Get PM data every 30s

### DISCUSSION THREAD

**Discussion by Kejszijo** [ajfriesen/ESPHome-AirGradient#28] [Q&A]
Hi,

Is it possible to retrieve the PM data every 30s with the Home Assistant? With Open Air device.
I would need it during the winter. I would monitor the air quality outside, and if it is bad, I would turn off the central ventilation system.

**Comment by ajfriesen** [comment]
Please check the docs for the sensor you are using:
https://esphome.io/components/sensor/pmsx003.html

```
# Example configuration entry
uart:
  rx_pin: GPIO23
  tx_pin: GPIO22
  baud_rate: 9600

sensor:
  - platform: pmsx003
    type: PMSX003
    pm_1_0:
      name: "Particulate Matter <1.0µm Concentration"
    pm_2_5:
      name: "Particulate Matter <2.5µm Concentration"
    pm_10_0:
      name: "Particulate Matter <10.0µm Concentration"
    update_interval: 120s
```
