### DISCUSSION TITLE
ESP8266 pins in yaml

### DISCUSSION THREAD

**Discussion by labatt** [ajfriesen/ESPHome-AirGradient#5] [General]
I had to modify my yaml file to map from the nodemcu pin scheme (i.e. d0, d1, etc.) to the esp8266 style:

```
i2c:
  sda: GPIO4
  scl: GPIO5
  
uart:
  - rx_pin: GPIO14
    tx_pin: GPIO12
    baud_rate: 9600
    id: uart1
  - rx_pin: GPIO2
    tx_pin: GPIO0
    baud_rate: 9600
    id: uart2

```
