### DISCUSSION TITLE
any updated version for the newAirGradient Pro (v3)?

### DISCUSSION THREAD

**Discussion by DariBer** [ajfriesen/ESPHome-AirGradient#9] [General]
Hi,

As there is a new updated version of AirGradient, Pro v3, I wonder if you will update your ESPHome so that it can be used with the new version and then have the data in Home Assistant.

/D

**Comment by ajfriesen** [comment]
I guess you are talking about this?

https://www.airgradient.com/open-airgradient/blog/airgradient-diy-pro-instructions/

I don't own the new version so I can not  verify.

But looking briefly at this it seems it's almost the same except a pin layout changed for one sensor.

So you may need to change that but other than that this should work almost the same.
Maybe a few adjustments.

If you happen to have one I will accept a PR for the new version.🙃

**Reply by handro123** [reply]
I based my config off @ajfriesen and got it working with my DIY Pro kit. There are some changes to get the different board and screen to work, and no TVOC sensor yet either. Here are the changes I made: https://github.com/handro123/AirGradient-DIY-Pro-ESPHome

**Reply by MichaelMure** [reply]
I did something similar.  For the TVOC sensor I used the following.

```
  - platform: sgp30
    eco2:
      id: eco2
      name: "eCO2"
      accuracy_decimals: 1
    tvoc:
      id: tvoc
      name: "TVOC"
      accuracy_decimals: 1
    store_baseline: yes
    address: 0x58
    update_interval: 60s
```

For some reason the `sht3xd` is still not working for me, but it might be a hardware problem.
